# Generated by Django 4.0.5 on 2022-06-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='데이터가 생성된 일자입니다.', verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='데이터를 수정한 일자입니다.', null=True, verbose_name='수정일')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'user_tb',
            },
        ),
    ]
