# Generated by Django 4.0.5 on 2022-06-15 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='데이터가 생성된 일자입니다.', verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='데이터를 수정한 일자입니다.', null=True, verbose_name='수정일')),
                ('name', models.CharField(max_length=100, verbose_name='회사이름')),
                ('nation', models.CharField(max_length=100, verbose_name='국가이름')),
                ('area', models.CharField(max_length=100, verbose_name='지역')),
            ],
            options={
                'verbose_name': '회사',
                'verbose_name_plural': '회사',
                'db_table': 'company_tb',
            },
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='데이터가 생성된 일자입니다.', verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='데이터를 수정한 일자입니다.', null=True, verbose_name='수정일')),
                ('position', models.CharField(max_length=100, verbose_name='포지션')),
                ('compensation', models.PositiveIntegerField(default=0, verbose_name='채용 보상금')),
                ('content', models.TextField(verbose_name='채용 내용')),
                ('skill', models.TextField(verbose_name='사용 기술')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='recruitment.company', verbose_name='회사')),
            ],
            options={
                'verbose_name': '채용공고',
                'verbose_name_plural': '채용공고',
                'db_table': 'job_opening_tb',
            },
        ),
        migrations.CreateModel(
            name='SupportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='데이터가 생성된 일자입니다.', verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='데이터를 수정한 일자입니다.', null=True, verbose_name='수정일')),
                ('job_opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_job_opening', to='recruitment.jobopening', verbose_name='채용공고')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_users', to='users.user', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '지원내역',
                'verbose_name_plural': '지원내역',
                'db_table': 'support_detail_tb',
            },
        ),
    ]
